[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[font]
size = 14.0 # Set your desired size

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

